### ISSUE TITLE
Falta Boton de ir a Inicio

### ISSUE THREAD

**Issue by AlexR1712** [UNEFAdev/forza#25]
![image](https://user-images.githubusercontent.com/8460736/39912524-02e335a6-54cd-11e8-9ab6-2ca07e264217.png)

**Comment by brandondrl** [comment]
ya fue colocado (Y)

**Comment by AlexR1712** [comment]
@brandondrl hasta que no este el PR no puedo dar como terminado la tarea, en adicion a eso debes referencia el commit
