### ISSUE TITLE
Buscar otra ubicacion para el boton de ver mas

### ISSUE THREAD

**Issue by AlexR1712** [UNEFAdev/forza#32]
![image](https://user-images.githubusercontent.com/8460736/39950831-4fbd206e-5552-11e8-9196-bbcde511a5ea.png)

**Comment by brandondrl** [comment]
este boton no hay mucho para donde moverlo creo, izquierda?

**Comment by AlexR1712** [comment]
izquierda mejor @brandondrl

**Comment by brandondrl** [comment]
![image](https://user-images.githubusercontent.com/19626753/39951774-1c58934e-555b-11e8-938c-dc7d5923fb0d.png)
 tipo como la imagen? para que parezca ribbon

**Comment by AlexR1712** [comment]
esta muy pegado pero si por alli mejor, porque no intercambias mejor el boton de ver mas a la derecha y lo de la meta data a la izquierda? @brandondrl

**Comment by brandondrl** [comment]
![image](https://user-images.githubusercontent.com/19626753/39951924-c5f4a022-555c-11e8-9e3f-63910a26fb87.png)
lo pegado es por lo del estilo ribbon, lo dejo asi o le coloco un margin? fijate invirtiendo el orden metadata-boton y no me parece que se vea bien, creo que esta mejor como la imagen que pase anteriormente @AlexR1712

**Comment by AlexR1712** [comment]
Por que no mejor lo separas lo indicado en la imagen de forma que quede en una linea todo?
![image](https://user-images.githubusercontent.com/8460736/39951972-37124b9c-555d-11e8-9163-243a32ca355f.png)

**Comment by AlexR1712** [comment]
@brandondrl si dejalo asi por mientras aunque aun no me gusta del todo

**Comment by brandondrl** [comment]
yo se que igual lo van a cambiar mañana 👎 @AlexR1712

**Comment by brandondrl** [comment]
listo -> d18b93b

**Comment by AlexR1712** [comment]
👍 Verificado procedo a cerrar issue
