### ISSUE TITLE
Botones de compartir en redes sociales no funciona

### ISSUE THREAD

**Issue by AlexR1712** [UNEFAdev/forza#33]
![image](https://user-images.githubusercontent.com/8460736/39950840-68e50458-5552-11e8-9c53-5b0e0d517bf4.png)

**Comment by brandondrl** [comment]
![image](https://user-images.githubusercontent.com/19626753/39952615-7510fc9e-5568-11e8-8141-1316a567119d.png)
 esto es lo que debo concatenar? @AlexR1712

**Comment by AlexR1712** [comment]
@brandondrl por favor examinar la url alli, o buscar en la documentacion de la red social

**Comment by brandondrl** [comment]
fue colocado el de facebook falta agregarle dinamismo y los de telegram y whatsapp

**Comment by brandondrl** [comment]
50% -> c357086
