### ISSUE TITLE
Los colaboradores deberian estar al final

### ISSUE THREAD

**Issue by AlexR1712** [UNEFAdev/forza#35]
![image](https://user-images.githubusercontent.com/8460736/39950904-196a18a4-5553-11e8-806e-d06320712784.png)

Mostrar los colaboradores al final en el footer y que esten con un texto mas pequeño

Colocar adicional, al final el siguiente copy: 

Universidad Nacional Experimental Politécnica de la Fuerza Armada Nacional - 2018 

Donde el 2018 debe ser variable o dinamico segun la fecha del usuario

**Comment by brandondrl** [comment]
listo -> 0882957

**Comment by AlexR1712** [comment]
Verificado
