### ISSUE TITLE
Agregar Discuss al final del visor de Post

### ISSUE THREAD

**Issue by AlexR1712** [UNEFAdev/forza#36]
Colocar disqus en el pie de pagina del post 

https://disqus.com

**Comment by brandondrl** [comment]
esto refiere a colocar un sistema de comentarios? @AlexR1712

**Comment by AlexR1712** [comment]
@brandondrl asi es

**Comment by brandondrl** [comment]
en discusion debido a que se entendia que la comunicacion seria unidireccional y esto implicaria la bidireccionalidad
