### ISSUE TITLE
Los colaboradores deben apuntar a la URL del perfil de Github si tiene cuenta la persona

### ISSUE THREAD

**Issue by AlexR1712** [UNEFAdev/forza#37]
![image](https://user-images.githubusercontent.com/8460736/39951016-efa7358c-5553-11e8-98c0-0755352084fa.png)

Por favor colocar aqui sus nombres de usuario:

Erickson ni siquiera esta como miembro del repositorio, no ha aceptado la invitacion

@ViT4RGh0ST  @brandondrl @AlexR1712

**Comment by brandondrl** [comment]
listo -> dc42e7b

**Comment by AlexR1712** [comment]
👍 Verificado procedo a cerrar issue
