### ISSUE TITLE
Colocar widgets de redes de la universidad

### ISSUE THREAD

**Issue by AlexR1712** [UNEFAdev/forza#38]
Widget de Twitter de la unefa nacional
![image](https://user-images.githubusercontent.com/8460736/39951050-4d8aa418-5554-11e8-9865-04ef92daec41.png)

- https://twitter.com/dsunefalara?lang=es
- https://twitter.com/unefa_ve
- https://www.instagram.com/dsunefalara/?hl=es-la

Documentaciones: 
- https://twitter.com/settings/widgets
- https://instawidget.net/generate

**Comment by brandondrl** [comment]
![image](https://user-images.githubusercontent.com/19626753/39951809-796dd9b8-555b-11e8-9c20-0565a47efb7b.png)
esos 3 widgets serán colocados aca? no te parece mucha informacion? creo que uno basta ademas que va con el diseño minimalista

**Comment by AlexR1712** [comment]
@brandondrl Eso es correcto

**Comment by brandondrl** [comment]
que es correcto? basta con uno o los 3 ahi? @AlexR1712

**Comment by AlexR1712** [comment]
@brandondrl los 3 para dar mayor detalle a los usuarios

**Comment by brandondrl** [comment]
entendido! @AlexR1712

**Comment by brandondrl** [comment]
los dos de twitter fueron colocados, el de instagram fue generado sin embargo el script que esta cargado en index hace render del widget en el body libremente y no en el div designado como los de twitter

**Comment by brandondrl** [comment]
50% ->c357086

**Comment by brandondrl** [comment]
https://stackoverflow.com/questions/45047126/how-to-add-external-js-scripts-to-vuejs-components?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa con esto creo que se soluciona lo del widget, seria cargar el script aca -> 
![image](https://user-images.githubusercontent.com/19626753/39953324-68a5c2aa-5577-11e8-9a22-48a6cfa1553f.png) @AlexR1712

**Comment by brandondrl** [comment]
ya esto esta listo no? @AlexR1712
