### ISSUE TITLE
Mejorar la vista de la pagina principal publica

### ISSUE THREAD

**Issue by brandondrl** [UNEFAdev/forza#4]

**Comment by AlexR1712** [comment]
@brandondrl esto no esta cerrado, te indico algunos cambios:

- [ ] Los botones de compartir no funcionan.
- [ ] Falta Boton que me permita volver al inicio de la pagina.
- [ ] Falta Spinner Loader para mostrar que la pagina esta cargando.
- [ ] Hay elementos que se cortan en la pantalla como por ejemplo el excerpt de los post de inicio.

**Comment by AlexR1712** [comment]
Realizando split de las task en este issue

**Comment by AlexR1712** [comment]
#60 #59 #23 #3
