### ISSUE TITLE
Titulo de los post deben ser clickeables

### ISSUE THREAD

**Issue by AlexR1712** [UNEFAdev/forza#68]
Navegando un momento en el sitio me di cuenta que es necesario poder acceder al post mediante el titulo tambien
![image](https://user-images.githubusercontent.com/8460736/40615759-21a4ebb0-6256-11e8-9297-ac7ee84e121b.png)

**Comment by AlexR1712** [comment]
@AlexR1712 this issue

**Comment by AlexR1712** [comment]
el problema que ahora se tiene es algo de estilo

**Comment by brandondrl** [comment]
resuelto el problema de estilos
